version: "3.8"
services:
    app:
        build: .
        container_name: script_tools
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - .:/app
            - /tmp/.X11-unix:/tmp/.X11-unix
        working_dir: /app
        stdin_open: true
        tty: true
    